--- # Poggit-CI Manifest. Open the CI at projects:
projects:
  translation:
    type: library
    model: virion
    path: ""
    libs:
      - src: JackNoordhuis/polyfill-mbstring/polyfill-mbstring
        version: 1.7.0
...
